//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Messages.proto
namespace KData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagesMsgConfig")]
  public partial class MessagesMsgConfig : global::ProtoBuf.IExtensible
  {
    public MessagesMsgConfig() {}
    

    private int _msg_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int msg_id
    {
      get { return _msg_id; }
      set { _msg_id = value; }
    }

    private string _msg_text = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg_text
    {
      get { return _msg_text; }
      set { _msg_text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagesMsgENConfig")]
  public partial class MessagesMsgENConfig : global::ProtoBuf.IExtensible
  {
    public MessagesMsgENConfig() {}
    

    private int _msg_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int msg_id
    {
      get { return _msg_id; }
      set { _msg_id = value; }
    }

    private string _msg_text = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg_text
    {
      get { return _msg_text; }
      set { _msg_text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagesMsgTCConfig")]
  public partial class MessagesMsgTCConfig : global::ProtoBuf.IExtensible
  {
    public MessagesMsgTCConfig() {}
    

    private int _msg_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int msg_id
    {
      get { return _msg_id; }
      set { _msg_id = value; }
    }

    private string _msg_text = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg_text
    {
      get { return _msg_text; }
      set { _msg_text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagesMsgSCConfig")]
  public partial class MessagesMsgSCConfig : global::ProtoBuf.IExtensible
  {
    public MessagesMsgSCConfig() {}
    

    private int _msg_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int msg_id
    {
      get { return _msg_id; }
      set { _msg_id = value; }
    }

    private string _msg_text = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg_text
    {
      get { return _msg_text; }
      set { _msg_text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}